; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Thu Dec 26 2019 17:05:21 GMT-0600 (Central Standard Time)
M561 ; clear any bed transform
G30 P0 X311 Y580 Z-99999 ; probe near a leadscrew
G30 P1 X20 Y164 Z-99999 ; probe near a leadscrew
G30 P2 X600 Y164 Z-99999 S3 ; probe near a leadscrew and calibrate 3 motors
G29  ; probe the bed and enable compensation
