; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Thu Dec 26 2019 17:05:23 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

